#!/usr/bin/env bash
# Made by Jesus Palencia, Hector Mantellini
# Licence: GPL-2
LC_ALL=C

minombre="UbuntuCodeofConduct-2.0.txt"

function malo() {
	rm -f /run/$(basename $0).pid
	exit 1
}

if [[ $(locale | grep LANG= | cut -d "=" -f2) != "es_VE.UTF-8" ]]; then
	echo -e "\e[00;31mERROR: Este script no puede ejecutarse en este ordenador por no estar configurado el locale correcto.\e[00m"
	malo
fi

function pause() {
	read -p "$*"
}

function check () {
	clear
	if [[ "$EUID" = "0" ]]; then
		echo -e "\e[00;31mERROR: No debe ser root.\e[00m"
		malo
	fi
	if ! [[ -f /usr/bin/xclip ]]; then
		echo -e "\e[00;31mDebe ejecutar la instalacion antes de continuar.\e[00m"
		malo
	fi
}

function limpio () {
	echo ""
	echo -e "\e[00;1;92mRealizando limpieza\e[00m"
	rm -f /tmp/genkey
	rm -f /tmp/listo
	rm -f /tmp/descifrado
	rm -f "$HOME"/correo.gpg
	rm -f "$HOME"/"$minombre"
	xclip -i /dev/null
	echo ""
}

function parame () {
	if ! [[ -z $2 ]]; then
		echo -e "\e[00;31mERROR: Se insertaron parametros innecesarios.\e[00m"
		malo
	fi
}

case "$1" in
	instalar)
		clear
		parame
		if [[ "$EUID" != "0" ]]; then
			echo -e "\e[00;31mERROR: Debe ser root.\e[00m"
			malo
		fi
		ver=$(lsb_release -c | awk '{print $2}')
		cp /etc/apt/sources.list /etc/apt/sources.list.old
		echo "deb http://archive.ubuntu.com/ubuntu/ $ver main restricted universe multiverse" > /etc/apt/sources.list
		echo "deb http://security.ubuntu.com/ubuntu/ $ver-security main restricted universe multiverse" >> /etc/apt/sources.list
		echo "deb http://archive.ubuntu.com/ubuntu/ $ver-updates main restricted universe multiverse" >> /etc/apt/sources.list
		apt-get -q update
		apt-get -qy install gnupg wget xclip beep
		apt-get clean
		mv -f /etc/apt/sources.list.old /etc/apt/sources.list
		if ! [[ -f $HOME/.gnupg/gpg.conf.old ]]; then
			mv -f $HOME/.gnupg/gpg.conf $HOME/.gnupg/gpg.conf.old
			echo "keyserver hkp://keys.gnupg.net" > $HOME/.gnupg/gpg.conf
			echo "fixed-list-mode" >> $HOME/.gnupg/gpg.conf
			echo "keyid-format 0xlong" >> $HOME/.gnupg/gpg.conf
			echo "with-fingerprint" >> $HOME/.gnupg/gpg.conf
			echo "personal-digest-preferences SHA512 SHA384 SHA256 SHA224" >> $HOME/.gnupg/gpg.conf
			echo "default-preference-list SHA512 SHA384 SHA256 SHA224 AES256 AES192 AES CAST5 BZIP2 ZLIB ZIP Uncompressed" >> $HOME/.gnupg/gpg.conf
			echo "use-agent" >> $HOME/.gnupg/gpg.conf
			echo "verify-options show-uid-validity" >> $HOME/.gnupg/gpg.conf
			echo "list-options show-uid-validit" >> $HOME/.gnupg/gpg.conf
			echo "sig-notation issuer-fpr@notations.openpgp.fifthhorseman.net=%g" >> $HOME/.gnupg/gpg.conf
			echo "cert-digest-algo SHA512" >> $HOME/.gnupg/gpg.conf
		fi
		echo -e "\e[00;1;92mInstalacion finalizada...\e[00m"
		;;

	gpg)
		check
		if [[ -z $2 ]]; then
			echo -e "\e[00;31mERROR: Faltan parametros.\e[00m"
			malo
		fi
		limpio
		echo -e "\e[00;1;92mDescargando el texto del codigo de conducta.\e[00m"
		wget -v -O "$HOME"/"$minombre" https://launchpad.net/codeofconduct/2.0/+download
		echo ""
		echo -e "\e[00;1;92mDescarga finalizada.\e[00m"
		echo ""
		echo -e "\e[00;1;92mPreparandose para generar llave GPG\e[00m"
		echo 'Key-Type: 1' > /tmp/genkey
		echo 'Key-Length: 2048' >> /tmp/genkey
		echo 'Subkey-Type: 1' >> /tmp/genkey
		echo 'Subkey-Length: 2048' >> /tmp/genkey
		echo 'Name-Real:' $2 $3 >> /tmp/genkey
		# echo 'Name-Comment: No comment' >> /tmp/genkey
		echo 'Name-Email:' $4 >> /tmp/genkey
		echo 'Expire-Date: 2y' >> /tmp/genkey
		echo -e "\e[00;1;92mGenerando llave GPG\e[00m"
		script -q /dev/stdout -c 'gpg --batch --gen-key /tmp/genkey' | tee /tmp/listo
		millave=$(cat /tmp/listo | grep "gpg: clave" | uniq | awk '{print $3}')
		export GPGKEY=$millave
		beep -r 3
		echo ""
		echo -e "\e[00;1;92mLlave GPG Generada.\e[00m"
		gpg --keyserver keyserver.ubuntu.com --send-keys $millave
		echo ""
		echo -e "\e[00;1;92mSe envio al keyserver de Ubuntu la siguiente llave: $millave\e[00m"
		mihuella=$(gpg --fingerprint $millave | grep "Huella de clave" | cut -c 25-74)
		echo "$mihuella" | xclip -selection c
		echo ""
		echo ""
		echo "Su huella esta almacenada temporalmente en el portapapeles."
		echo "Siga las instrucciones a continuacion:"
		echo ""
		echo "1.- Abrir Launchpad.net en su navegador favorito y loguearse."
		echo ""
		echo "2.- Ir a firmar codigo de conducta."
		echo ""
		echo "3.- Registrar su nueva llave, en el campo fingerprint pegue lo que esta en el portapapeles (ctrl + v)"
		echo "    presione el boton [Import Key]"
		echo ""
		echo "4.- Una vez realizada la accion anterior se le enviara un correo de confirmacion."
		echo ""
		echo "5.- Abra el correo que dice en el asunto: Launchpad: Confirm your OpenPGP Key"
		echo "    copie el texto en el bloque gpg y peguelo en el bloc de notas, luego guardelo en su directorio /home/SU_USUARIO con el nombre correo.gpg"
		echo ""
		echo "6.- Luego presione Enter en la pantalla de la consola, donde se ejecuta el script"
		echo "    se abrira una ventana del navegador por default donde hara clic en confirmar."
		echo ""
		echo "7.- Vaya de nuevo a firmar Codigo de Conducta y seleccione la opcion: 3 Sign it! (Firmar)"
		echo ""
		echo "8.- Pegue el contenido del portapapeles y presione continuar."
		echo ""
		pause "Presione Enter para continuar."
		xclip -i /dev/null
		echo -e "\e[00;1;92mDescifrando el archivo correo.gpg\e[00m"
		gpg --decrypt "$HOME"/correo.gpg > /tmp/descifrado
		decrypt=$(cat /tmp/descifrado | grep https: | awk '{print $1}')
		firefox $decrypt
		pause "Presione Enter para continuar."
		echo ""
		echo -e "\e[00;1;92mSe firmara el codigo de conducta.\e[00m"
		gpg --clearsign -u $millave "$HOME"/"$minombre"
		echo ""
		echo -e "\e[00;1;92mEl codigo de conducta ha sido firmado.\e[00m"
		cat "$HOME"/"$minombre".asc | xclip -selection c
		echo ""
		echo "Vaya a launchpad.net y presione ctrl + v para pegar el contenido del codigo de conducta ya firmado."
		echo ""
		pause "Luego de pegar el contenido presione Enter para finalizar."
		limpio
		echo -e "\e[00;1;92mFinalizado...\e[00m"
		;;

	ssh)
		check
		parame
		limpio
		echo -e "\e[00;1;92mGenerando llave SSH\e[00m"
		ssh-keygen -b 1024 -t rsa -f "$HOME"/.ssh/id_rsa -N ''
		echo ""
		echo -e "\e[00;1;92mLLave SSH generada.\e[00m"
		cat "$HOME"/.ssh/id_rsa.pub | xclip -selection c
		echo ""
		echo "Su llave SSH esta almacenada temporalmente en el portapapeles."
		echo ""
		echo "1.- Vaya a launchpad.net y haga clic en: ssh keys"
		echo ""
		echo "2.- Pegue (ctrl + v) el contenido del portapapeles y presione: importar public key"
		echo ""
		pause "Luego de pegar el contenido presione Enter para finalizar."
		limpio
		echo -e "\e[00;1;92mFinalizado...\e[00m"
		;;

	*)
            	echo "USO: cocsign {instalar|gpg|ssh} nombre apellido sudireccion@correo.com"
		;;

esac
exit 0
